### ISSUE TITLE
Client Error: Not Found for url

### ISSUE THREAD

**Issue by mynameisguy** [btcpayserver/btcpay-python#17]
When running `BTCPayClient.create_client` I'm getting the error:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://*******/tokens
```

I do have a working SSL certificate (checked due to https://github.com/btcpayserver/btcpay-python/issues/11#issuecomment-572736002).

The issue might be the different certificates:
* BTCPay - Let's encrypt (used this [tutorial](https://wiki.ion.radar.tech/tutorials/nodes/btcpay-+-aws-ec2) to deploy)
* webhook server - AWS Certificate

Both have the same domain, different subdomains.

Is there any way around this or should I somehow make sure they use the same certificate?

**Comment by mynameisguy** [comment]
I actually don't think it's the issue.
I tried to connect from my local machine and I'm getting the same error.

I'm getting a different error when trying to use http instead of https

```python
>>> BTCPayClient.create_client(host='https://*********', code="1L7By9f")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../env/lib/python3.8/site-packages/btcpay/client.py", line 142, in create_client
    token = client.pair_client(code)
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 132, in pair_client
    data = self._unsigned_request('/tokens', payload)
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 84, in _unsigned_request
    r.raise_for_status()
  File "/.../venv/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://*********/tokens
>>> BTCPayClient.create_client(host='http://*********', code="1L7By9f")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 142, in create_client
    token = client.pair_client(code)
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 133, in pair_client
    data = data[0]
IndexError: list index out of range
```

**Comment by mynameisguy** [comment]
I actually don't think it's the issue.
I tried to connect from my local machine and I'm getting the same error.
I'm getting a different error when trying to use http instead of https

```python
>>> BTCPayClient.create_client(host='https://*********', code="***")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../env/lib/python3.8/site-packages/btcpay/client.py", line 142, in create_client
    token = client.pair_client(code)
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 132, in pair_client
    data = self._unsigned_request('/tokens', payload)
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 84, in _unsigned_request
    r.raise_for_status()
  File "/.../venv/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://*********/tokens
>>> BTCPayClient.create_client(host='http://*********', code="***")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 142, in create_client
    token = client.pair_client(code)
  File "/.../venv/lib/python3.8/site-packages/btcpay/client.py", line 133, in pair_client
    data = data[0]
IndexError: list index out of range
```

**Comment by mynameisguy** [comment]
Not sure why, but it's working now 🤷‍♂️
