### ISSUE TITLE
Client not found error

### ISSUE THREAD

**Issue by reablaz** [btcpayserver/btcpay-python#2]
Hello!

I'm getting issue with any client action:

1) Generated key
2) Paired with server
3) Trying to get_rates() or gen_Invoice(), but getting this error:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    client.get_rates()
  File "/usr/local/lib/python3.6/site-packages/btcpay/client.py", line 74, in get_rates
    return self._signed_get_request('/rates/', params=params)
  File "/usr/local/lib/python3.6/site-packages/btcpay/client.py", line 45, in _signed_get_request
    r.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: %mybtcpayurl%

**Comment by NicolasDorier** [comment]
hey sorry just saw that now. The bug has been fixed yestersday. If you update your BTCPay server it will work.

**Comment by reablaz** [comment]
Now it works
Many thanks, Nicolas!
