### ISSUE TITLE
Trouble pairing

### ISSUE THREAD

**Issue by justinmoon** [btcpayserver/btcpay-python#3]
Here's my test program directly following the README:

```
import btcpay.crypto
from btcpay import BTCPayClient

URL = "https://test.buidlbootcamp.com"

privkey = btcpay.crypto.generate_privkey()
client = BTCPayClient(
    host=URL, 
    pem=privkey,
)

pairing_code = "SECRET!!!"
tokens = client.pair_client(pairing_code)

print(client.get_rates())
```

I encounter this exception:
```
$ python script.py 
Traceback (most recent call last):
  File "script.py", line 13, in <module>
    tokens = client.pair_client(pairing_code)
  File "/home/justin/dev/buidl-treasury/venv/lib/python3.7/site-packages/btcpay/client.py", line 97, in pair_client
    data = self._unsigned_request('/tokens', payload)
  File "/home/justin/dev/buidl-treasury/venv/lib/python3.7/site-packages/btcpay/client.py", line 65, in _unsigned_request
    r.raise_for_status()
  File "/home/justin/dev/buidl-treasury/venv/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://test.buidlbootcamp.com/tokens
```

This server is on testnet FWIW

**Comment by NicolasDorier** [comment]
Your pairing code got approved?

**Comment by justinmoon** [comment]
I generated a new pairing code and it looks like the pairing succeeded, but `get_rates()` failed ...

```$ python script.py 
Traceback (most recent call last):
  File "script.py", line 15, in <module>
    print(client.get_rates())
  File "/home/justin/dev/buidl-treasury/venv/lib/python3.7/site-packages/btcpay/client.py", line 74, in get_rates
    return self._signed_get_request('/rates/', params=params)
  File "/home/justin/dev/buidl-treasury/venv/lib/python3.7/site-packages/btcpay/client.py", line 37, in _signed_get_request
    token = token or list(self.tokens.values())[0]
IndexError: list index out of range
```

**Comment by justinmoon** [comment]
I see the problem

**Comment by NicolasDorier** [comment]
ah for the `get_rates` might be a bug I fixed yestersday, can `test.buidlbootcamp.com` update their BTCPay?

**Comment by justinmoon** [comment]
Yes it can. I just set it up today and can change anything.

**Comment by justinmoon** [comment]
OK I did a successful pairing. I didn't understand and was trying to re-pair every time the script ran. Now I just have the `{'merchant': '...'}` tokens dictionary hard-coded into my script.

**Comment by justinmoon** [comment]
I successfully executed `BTCPayClient.get_rates` and `BTCPayClient.create_invoice`.

My issue was just that I didn't understand the pairing model -- that the private key we were generating was to correspond with the "pairing code" generated on the BTCPayServer instance ...

Sorry to bother you!

**Comment by NicolasDorier** [comment]
yeah legacy shit from bitpay. I hope we will propose better API later.
