### ISSUE TITLE
SSL Verification Error

### ISSUE THREAD

**Issue by Tomasvrba** [btcpayserver/btcpay-python#8]
I have deployed BTCPAY on a Digital Ocean server for testing (btc testnet), and everything is working fine so far except for when I try to create a client in python to connect to the server. 

I have generated the pairing code in the server dashboard, but each time I try to create the client in python I get the following SSL errors:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=XXX, port=443): Max retries exceeded with url: /tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/btcpay/client.py", line 134, in pair_client
    data = self._unsigned_request('/tokens', payload)
  File "/usr/local/lib/python3.7/site-packages/btcpay/client.py", line 81, in _unsigned_request
    r = self.s.post(uri, data=payload)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host=XXX, port=443): Max retries exceeded with url: /tokens (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
```

When I log the nginx container, I can only see on POST request come in for the /token url for each client connection attempt  
`[30/Jul/2019:13:28:22 +0000] "POST /tokens HTTP/1.1" 301 162 "-" "python-requests/2.22.0"`),  
though the SSL error (`Max retries exceeded with url: /tokens`) makes it seem like it was denied because of too many requests

I did have to add a security exception to access my btcpay website so perhaps the cert wasn't configured properly during the docker setup?

**Comment by JeffVandrewJr** [comment]
Hey, hope all is well! This is not an issue with the Python library but rather an issue with your server setup, as evidenced by the fact that you had to add a security exception to even access your site (which should not have been necessary). I've never used Digital Ocean specifically so I'm not a ton of help there. 

I'm closing the issue here only because it doesn't relate to the Python library, so this isn't the best venue to post it. You'll get more help elsewhere where there will be more forum participants who are more familiar with server configuration issues than I am. You may wish to seek support in chat.btcpayserver.org or on the GitHub page for BTCPayServer-Docker. I would be sure to specify that you had to add a security exception to access the site at all, and that your API pairing isn't working due to SSL errors.

**Comment by NicolasDorier** [comment]
@Tomasvrba if the certificate is fine in your browser, then you need to install certificates on the client machine. It depends on your OS, so I can't help either.

**Comment by Tomasvrba** [comment]
Thanks!
I ended up re-running the entire setup, this time with a different setting for `ACME_CA_URI` and that resolved the issue.
